### ISSUE TITLE
Its not working anymore

### ISSUE THREAD

**Issue by ItzOrion** [jacky917/Rapidgator-DL-Extension#1]
I am not able to download , it keep giving this error
![Screenshot (64)](https://github.com/jacky917/Rapidgator-DL-Extension/assets/136430962/90568af9-11af-4877-a3bd-b899d66570f5)
![Screenshot (65)](https://github.com/jacky917/Rapidgator-DL-Extension/assets/136430962/d74b1057-3bc4-4fb8-8a5d-6a751ef8c501)

PLEASE FIX THIS!!
Thank You , its really a great tool i am very grateful to you
You Are AMAZING!!!!!

**Comment by AbaddonGamer** [comment]
I keep getting this error since today
![Screenshot 2023-07-10 123907](https://github.com/jacky917/Rapidgator-DL-Extension/assets/64578820/421cc51f-7150-4f76-a624-52301649a9bc)

Please fix this if you can
It is a really useful tool 
Thank you

**Comment by nakheel77** [comment]
today,  it dont work for me. please update. many thanks

**Comment by jacky917** [comment]
I'm very sorry, but since the bandwidth for Rapidgator requires a paid subscription, I can't provide services for free in the long term. Currently, the bandwidth is almost depleted, so I've temporarily stopped offering services publicly. If you want to know when it might be available again (although it may not be), you could join our QQ group.

**Comment by ItzOrion** [comment]
Can you  introduce an ad based service like an link shortener for every download link created ,this way you can get passive income   and continue providing this amazing service !!!

**Comment by jacky917** [comment]
Okay, I'll think about it.

**Comment by ItzOrion** [comment]
Would really appreciate if this project moves forward!
